### ISSUE TITLE
blasfeo_d_blas.h docu

### ISSUE THREAD

**Issue by FreyJo** [giaf/blasfeo#10]
I just got really confused by this:

// y = y + alpha*x
void daxpy_libstr(int kmax, double alpha, struct d_strvec *sx, int xi, struct d_strvec *sy, int yi, struct d_strvec *sz, int zi);

Wondering what z is used for. I guess the comment should be z=y+alpha*x.
There are some similar comments in this .h file.
Fixing these comments, would make blasfeo easier to use for beginners, like me, i guess.

**Comment by giaf** [comment]
Thank you for pointing that out.

**Comment by giaf** [comment]
This should fix the issue you report
https://github.com/giaf/blasfeo/commit/572a782baee74372783a227bb063c116c10cbcdc
are there more?

**Comment by FreyJo** [comment]
Seems to be correct now, thanks!

**Comment by FreyJo** [comment]
Hey Gianluca,

I found some similar comments here:
https://github.com/giaf/blasfeo/blob/master/include/blasfeo_d_aux.h

// y <= x
void dveccp_libstr(int m, struct d_strvec *sa, int ai, struct d_strvec *sc,
int ci);
// x <= alpha*x
void dvecsc_libstr(int m, double alpha, struct d_strvec *sa, int ai);

Best regards
Jonathan
