### ISSUE TITLE
benchmarks/cpu_freq.h.example licensed under GPL3 + classpath

### ISSUE THREAD

**Issue by nielsvd** [giaf/blasfeo#125]
The file ``benchmarks/cpu_freq.h.example`` is licensed under GPL3 + classpath. Is this intentional? It's alway a bit tricky to combine GPL with other licenses in one project. Due to the class-path exception, particularly for source distributions.

**Comment by tmmsartor** [comment]
No I don't think It is intentional, #126  should fix

**Comment by giaf** [comment]
Yes it was just a left over from the old licence.
