### ISSUE TITLE
BLASFEO_PROCESSOR_FEATURES as identifier instead of object

### ISSUE THREAD

**Issue by wdecre** [giaf/blasfeo#137]
We are using Blasfeo in our research project. If we have multiple compilation units in the library we are developing, we get linking errors as the object BLASFEO_PROCESSOR_FEATURES gets defined multiple times:

https://github.com/giaf/blasfeo/blob/37effdac770a8bd2f6dc64f205d8d151dcd8b73d/include/blasfeo_processor_features.h#L42

We did not find where BLASFEO_PROCESSOR_FEATURES is used as an object, but maybe we missed something (could be depending on the options). Perhaps the idea was to use BLASFEO_PROCESSOR_FEATURES as an identifier instead of an object? Or is there a reason for it?

	enum BLASFEO_PROCESSOR_FEATURES
	{
		// x86-64 CPU features
		BLASFEO_PROCESSOR_FEATURE_AVX  = 0x0001,    /// AVX instruction set
		BLASFEO_PROCESSOR_FEATURE_AVX2 = 0x0002,    /// AVX2 instruction set
		BLASFEO_PROCESSOR_FEATURE_FMA  = 0x0004,    /// FMA instruction set
		BLASFEO_PROCESSOR_FEATURE_SSE3 = 0x0008,    /// SSE3 instruction set

		// ARM CPU features
		BLASFEO_PROCESSOR_FEATURE_VFPv3  = 0x0100,  /// VFPv3 instruction set
		BLASFEO_PROCESSOR_FEATURE_NEON   = 0x0100,  /// NEON instruction set
		BLASFEO_PROCESSOR_FEATURE_VFPv4  = 0x0100,  /// VFPv4 instruction set
		BLASFEO_PROCESSOR_FEATURE_NEONv2 = 0x0100,  /// NEONv2 instruction set
	};

Thank you,
Wilm and Lander

**Comment by giaf** [comment]
@imciner2 do you want to have a look at it, or should I do it?

**Comment by imciner2** [comment]
Sorry, this slipped through my inbox due to an overload of mail at the time. Yes, there is currently no use of it as an object - I had originally thought of using it as an object type, but then decided to just use them as flags that could be combined as well (since that is what we actually care about). So the change to make it just an identifier is fine.

**Comment by wdecre** [comment]
cf. commit a96c518e1c92b4448ccf774187baf742b663e648.
