### ISSUE TITLE
Need to link against math library?

### ISSUE THREAD

**Issue by bjack205** [giaf/blasfeo#149]
I'm getting a linker error on both gcc-10 and clang-12 compilers, complaining about an undefined reference to `sqrt`. This is fixed by changing the library to link against the math library:

```
target_link_libraries(blasfeo
    PRIVATE
    m
)
```

I'm on Pop!_OS 21.04 with an Intel i7-1165G7 CPU. Not sure why this is an issue on my machine but apparently not on others.

**Comment by giaf** [comment]
Hi Brian, thanks for the issue report.

First of all, I'm not very familiar with `cmake` and other people have mainly developed the `cmake` build system, but:
1) apparently on my ubuntu 20.04 standard toolchain it is not necessary to explicitly add the math library, both static and shared libraries compile just fine as it is, but I agree this is very system dependent
2) if I recall correctly I happen to hear that adding explicitly `m` would fail on visual studio, or something like that

So I guess the safe way of doing would be to add a check for the used compiler and only add the `m` library if supported.
