### ISSUE TITLE
Incorrect documentation for dtrmm in blasfeo_d_blasfeo_api.h?

### ISSUE THREAD

**Issue by markisus** [giaf/blasfeo#161]
These two functions have the same description but one is `llnn` and the other is `llnu`
https://github.com/giaf/blasfeo/blob/eb0568f18b2aaa49954ca9e92215d2cfe3dd5aa2/include/blasfeo_d_blasfeo_api.h#L169 
https://github.com/giaf/blasfeo/blob/eb0568f18b2aaa49954ca9e92215d2cfe3dd5aa2/include/blasfeo_d_blasfeo_api.h#L171

The same issue applies to many of the other functions for the `dtrmm`. I believe the `llnn` translates to 
1. l: multiply from the [l]eft
2. l: [l]ower triangular
3. n: [n]ot transposed
4. n: ? not sure what the last n stands for

**Comment by markisus** [comment]
From cross-referencing LAPACK documentation http://www.netlib.org/lapack/explore-html/d1/d54/group__double__blas__level3_gaf07edfbb2d2077687522652c9e283e1e.html I believe the last letter corresponds to whether the matrix is [u]nit diagonal or [n]ot.

**Comment by giaf** [comment]
Yes I confirm that this is correct.
Thanks for reporting the issue, that has now been improved in the header files. https://github.com/giaf/blasfeo/commit/504d0ec80cd5c940f030a03afdbc5bb9ee7d72be
