### ISSUE TITLE
Calling certain triangular matrices routines leads to `undefined symbol` error

### ISSUE THREAD

**Issue by yzuuang** [giaf/blasfeo#171]
When I try to call either of these following routines, `blasfeo_dtrmm_lunn`, `blasfeo_dtrmm_lutn`, `blasfeo_dtrmm_rltn`, I will encounter the error, though `blasfeo_dtrmm_rlnn` works fine

**Comment by giaf** [comment]
Can you give some more details so I can reproduce the issue?
E.g. branch, make/cmake, TARGET, LA, MF, BLASFEO_REF_API, OS.
And equally importantly which symbol is undefined and which triangular routines lead to the issue?

**Comment by giaf** [comment]
Indeed it looked like some dtrmm routines were missing.
Now the missing ones are implemented using callbacks to reference code https://github.com/giaf/blasfeo/commit/3f4e7f51bda234b9302bcf3dbec259101f724797
If performance of some of these routines is a priority, an optimized version can be implemented.
