### ISSUE TITLE
Any interest in tagging a new release?

### ISSUE THREAD

**Issue by traversaro** [giaf/blasfeo#181]
Hello @giaf, thanks a lot for the great work on blasfeo! 

I am looking in packaging blasfeo for conda-forge (https://conda-forge.org/), and I noticed that the latest release does not contain some quite interesting fixes that were merged in master. Would you be interested in doing a new release/tag on the repo? That may be useful for downstream package for the library. 

If you are interested and you need any kind of help/support that can come from outside contributors on making the release, feel free to ask.

Thanks a lot in advance!

**Comment by giaf** [comment]
Hi,

thanks for the interest and the suggestion. I would make a new release in the coming weeks, together with a new HPIPM one, once I'm done with some small feature I'm working on in there.

**Comment by traversaro** [comment]
Great, thanks a lot!

**Comment by RSchwan** [comment]
I'm in the process of integrating blasfeo into a library of mine, which is also hosted on conda. Thus, it would be great if I could use the blasfeo conda package to keep the dependencies clean. Unfortunately, the distributed conda package is quite old and linux only. Hence, a new blasfeo release would be much appreciated :)

@traversaro: I managed to compile specialized architectures on Windows using clang-cl. The libraries created are also compatible with downstream MSVC projects. As soon as there is a new release, I can create a PR to the blasfeo-feedstock with the appropriate changes.

**Comment by traversaro** [comment]
> As soon as there is a new release, I can create a PR to the blasfeo-feedstock with the appropriate changes.

Thanks in advance!

**Comment by giaf** [comment]
Thanks for the patience, I'm almost there with the planned changes before the new release!

**Comment by giaf** [comment]
Here you go https://github.com/giaf/blasfeo/releases
