### ISSUE TITLE
make on Mac OSX: Automatic detection of operating system?

### ISSUE THREAD

**Issue by roversch** [giaf/blasfeo#2]
Before `make`, I need to put into comment `OS = LINUX` and uncomment `#OS = MAC` in `Makefile.rule`. Can't this be done automatically? 

See e.g. [http://stackoverflow.com/questions/714100/os-detecting-makefile]

**Comment by giaf** [comment]
Thanks for implementing OS detection! 

About architecture detection, I prefer to avoid that for the time being, as I need to switch between them all the time. Maybe at some point I can implement something that detects it, but can be overwritten by user choice.
