### ISSUE TITLE
How to compile armv7 library on linux?

### ISSUE THREAD

**Issue by yongjong111** [giaf/blasfeo#54]
I'm a earlier.
I have changed target to armv7 in Makefile.rule and make.
but error occur.
gcc: error :unreconized command line option '-mfpu=neon-vfpv4'
what do i have to do?
thanks in advance.

**Comment by giaf** [comment]
Hi there,

ARMv7A cores have several options for the FP unit, see e.g.
https://en.wikipedia.org/wiki/ARM_architecture#Floating-point_(VFP)

The optimized assembly code in the CORTEX_A15 target in BLASFEO assumes (at least) version 4 of the FPU with 32 registers and NEON, and the gcc flag enables the compiler to generate code for this configuration.

If you have a different FPU and/or an older compiler, you may need to use the GENERIC target in BLASFEO, possibly adding yourself some C flags to enable the use of the floating point unit.

**Comment by yongjong111** [comment]
Thanks for your fast reply.
i have just upgraded gcc version to 8.0.1 from 5.0.2 but same error.
i checked for other fpu version, ex : vfpv3, vfpv4 but same error.

**Comment by yongjong111** [comment]
when i remove -mfpu option from Makefile.rule, got following errors.


hch@hch-ThinkPad-E-series-E570:~/Documents/blasfeo/blasfeo-master$ make
make -C auxiliary clean
make[1]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/auxiliary'
rm -f *.o
make[1]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/auxiliary'
make -C kernel clean
make[1]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel'
make -C avx2 clean
make[2]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/avx2'
rm -f *.o
rm -f *.s
make[2]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/avx2'
make -C avx clean
make[2]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/avx'
rm -f *.o
rm -f *.s
make[2]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/avx'
make -C sse3 clean
make[2]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/sse3'
rm -f *.o
rm -f *.s
make[2]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/sse3'
make -C fma clean
make[2]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/fma'
rm -f *.o
rm -f *.s
make[2]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/fma'
make -C armv8a clean
make[2]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/armv8a'
rm -f *.o
rm -f *.s
make[2]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/armv8a'
make -C armv7a clean
make[2]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/armv7a'
rm -f *.o
rm -f *.s
make[2]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/armv7a'
make -C c99 clean
make[2]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/c99'
rm -f *.o
rm -f *.s
make[2]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/c99'
make[1]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel'
make -C blas clean
make[1]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/blas'
rm -f *.o
rm -f *.s
make[1]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/blas'
make -C examples clean
make[1]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/examples'
rm -rf ./*.o
rm -rf ./*.out
rm -rf ./build/HIGH_PERFORMANCE/ARMV7A_ARM_CORTEX_A15/*
make[1]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/examples'
make -C tests clean
make[1]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/tests'
rm -rf ./*.o
rm -rf ./*.out
rm -rf ./build/HIGH_PERFORMANCE/ARMV7A_ARM_CORTEX_A15/*
make[1]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/tests'
make -C benchmarks clean
make[1]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/benchmarks'
rm -rf ./*.o
rm -rf ./*.out
rm -rf ./build/HIGH_PERFORMANCE/ARMV7A_ARM_CORTEX_A15/*
make[1]: Leaving directory '/home/hch/Documents/blasfeo/blasfeo-master/benchmarks'
touch ./include/blasfeo_target.h
echo "#ifndef TARGET_ARMV7A_ARM_CORTEX_A15" > ./include/blasfeo_target.h
echo "#define TARGET_ARMV7A_ARM_CORTEX_A15" >> ./include/blasfeo_target.h
echo "#endif" >> ./include/blasfeo_target.h
echo "#ifndef LA_HIGH_PERFORMANCE" >> ./include/blasfeo_target.h
echo "#define LA_HIGH_PERFORMANCE" >> ./include/blasfeo_target.h
echo "#endif" >> ./include/blasfeo_target.h
echo "#ifndef EXT_DEP" >> ./include/blasfeo_target.h
echo "#define EXT_DEP" >> ./include/blasfeo_target.h
echo "#endif" >> ./include/blasfeo_target.h
( cd kernel; make obj)
make[1]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel'
( cd armv7a; make obj)
make[2]: Entering directory '/home/hch/Documents/blasfeo/blasfeo-master/kernel/armv7a'
gcc   -DMIN_KERNEL_SIZE=2 -DOS_LINUX -DTARGET_ARMV7A_ARM_CORTEX_A15   -c -o kernel_dgemm_4x4_lib4.o kernel_dgemm_4x4_lib4.S
kernel_dgemm_4x4_lib4.S: Assembler messages:
kernel_dgemm_4x4_lib4.S:59: Error: expecting operand after ','; got nothing
kernel_dgemm_4x4_lib4.S:60: Error: no such instruction: `ble 2f'
kernel_dgemm_4x4_lib4.S:63: Error: no such instruction: `pld [r5,'
kernel_dgemm_4x4_lib4.S:64: Error: no such instruction: `pld [r6,'
kernel_dgemm_4x4_lib4.S:67: Error: no such instruction: `fldd d16,[r5,'
kernel_dgemm_4x4_lib4.S:68: Error: no such instruction: `fldd d17,[r5,'
kernel_dgemm_4x4_lib4.S:69: Error: no such instruction: `fldd d18,[r5,'
kernel_dgemm_4x4_lib4.S:70: Error: no such instruction: `fldd d19,[r5,'
kernel_dgemm_4x4_lib4.S:73: Error: no such instruction: `fldd d20,[r6,'
kernel_dgemm_4x4_lib4.S:74: Error: no such instruction: `fldd d21,[r6,'
kernel_dgemm_4x4_lib4.S:75: Error: no such instruction: `fldd d22,[r6,'
kernel_dgemm_4x4_lib4.S:76: Error: no such instruction: `fldd d23,[r6,'
kernel_dgemm_4x4_lib4.S:79: Error: no such instruction: `fldd d24,[r5,'
kernel_dgemm_4x4_lib4.S:80: Error: no such instruction: `fldd d25,[r5,'
kernel_dgemm_4x4_lib4.S:81: Error: no such instruction: `fldd d26,[r5,'
kernel_dgemm_4x4_lib4.S:82: Error: no such instruction: `fldd d27,[r5,'
kernel_dgemm_4x4_lib4.S:85: Error: no such instruction: `fldd d28,[r6,'
kernel_dgemm_4x4_lib4.S:86: Error: no such instruction: `fldd d29,[r6,'
kernel_dgemm_4x4_lib4.S:87: Error: no such instruction: `fldd d30,[r6,'
kernel_dgemm_4x4_lib4.S:88: Error: no such instruction: `fldd d31,[r6,'
kernel_dgemm_4x4_lib4.S:91: Error: no such instruction: `pld [r5,'
kernel_dgemm_4x4_lib4.S:92: Error: no such instruction: `pld [r6,'
kernel_dgemm_4x4_lib4.S:94: Error: expecting operand after ','; got nothing
kernel_dgemm_4x4_lib4.S:95: Error: no such instruction: `ble 0f'
kernel_dgemm_4x4_lib4.S:101: Error: no such instruction: `fmacd d0,d16,d20'
kernel_dgemm_4x4_lib4.S:102: Error: no such instruction: `pld [r5,'
kernel_dgemm_4x4_lib4.S:103: Error: no such instruction: `fmacd d1,d17,d20'
kernel_dgemm_4x4_lib4.S:104: Error: no such instruction: `pld [r6,'
kernel_dgemm_4x4_lib4.S:105: Error: no such instruction: `fmacd d2,d18,d20'
kernel_dgemm_4x4_lib4.S:106: Error: no such instruction: `fmacd d3,d19,d20'
kernel_dgemm_4x4_lib4.S:107: Error: no such instruction: `fldd d20,[r6,'
kernel_dgemm_4x4_lib4.S:109: Error: no such instruction: `fmacd d4,d16,d21'
kernel_dgemm_4x4_lib4.S:110: Error: no such instruction: `fmacd d5,d17,d21'
kernel_dgemm_4x4_lib4.S:111: Error: no such instruction: `fmacd d6,d18,d21'
kernel_dgemm_4x4_lib4.S:112: Error: no such instruction: `fmacd d7,d19,d21'
kernel_dgemm_4x4_lib4.S:113: Error: no such instruction: `fldd d21,[r6,'
kernel_dgemm_4x4_lib4.S:115: Error: no such instruction: `fmacd d8,d16,d22'
kernel_dgemm_4x4_lib4.S:116: Error: no such instruction: `fmacd d9,d17,d22'
kernel_dgemm_4x4_lib4.S:117: Error: no such instruction: `fmacd d10,d18,d22'
kernel_dgemm_4x4_lib4.S:118: Error: no such instruction: `fmacd d11,d19,d22'
kernel_dgemm_4x4_lib4.S:119: Error: no such instruction: `fldd d22,[r6,'
kernel_dgemm_4x4_lib4.S:121: Error: no such instruction: `fmacd d12,d16,d23'
kernel_dgemm_4x4_lib4.S:122: Error: no such instruction: `fldd d16,[r5,'
kernel_dgemm_4x4_lib4.S:123: Error: no such instruction: `fmacd d13,d17,d23'
kernel_dgemm_4x4_lib4.S:124: Error: no such instruction: `fldd d17,[r5,'
kernel_dgemm_4x4_lib4.S:125: Error: no such instruction: `fmacd d14,d18,d23'
kernel_dgemm_4x4_lib4.S:126: Error: no such instruction: `fldd d18,[r5,'
kernel_dgemm_4x4_lib4.S:127: Error: no such instruction: `fmacd d15,d19,d23'
kernel_dgemm_4x4_lib4.S:128: Error: no such instruction: `fldd d19,[r5,'
kernel_dgemm_4x4_lib4.S:129: Error: no such instruction: `fldd d23,[r6,'
kernel_dgemm_4x4_lib4.S:132: Error: no such instruction: `fmacd d0,d24,d28'
kernel_dgemm_4x4_lib4.S:133: Error: no such instruction: `fmacd d1,d25,d28'
kernel_dgemm_4x4_lib4.S:134: Error: no such instruction: `fmacd d2,d26,d28'
kernel_dgemm_4x4_lib4.S:135: Error: no such instruction: `fmacd d3,d27,d28'
kernel_dgemm_4x4_lib4.S:136: Error: no such instruction: `fldd d28,[r6,'
kernel_dgemm_4x4_lib4.S:138: Error: no such instruction: `fmacd d4,d24,d29'
kernel_dgemm_4x4_lib4.S:139: Error: no such instruction: `fmacd d5,d25,d29'
kernel_dgemm_4x4_lib4.S:140: Error: no such instruction: `fmacd d6,d26,d29'
kernel_dgemm_4x4_lib4.S:141: Error: no such instruction: `fmacd d7,d27,d29'
kernel_dgemm_4x4_lib4.S:142: Error: no such instruction: `fldd d29,[r6,'
kernel_dgemm_4x4_lib4.S:144: Error: no such instruction: `fmacd d8,d24,d30'
kernel_dgemm_4x4_lib4.S:145: Error: no such instruction: `fmacd d9,d25,d30'
kernel_dgemm_4x4_lib4.S:146: Error: no such instruction: `fmacd d10,d26,d30'
kernel_dgemm_4x4_lib4.S:147: Error: no such instruction: `fmacd d11,d27,d30'
kernel_dgemm_4x4_lib4.S:148: Error: no such instruction: `fldd d30,[r6,'
kernel_dgemm_4x4_lib4.S:150: Error: no such instruction: `fmacd d12,d24,d31'
kernel_dgemm_4x4_lib4.S:151: Error: no such instruction: `fldd d24,[r5,'
kernel_dgemm_4x4_lib4.S:152: Error: no such instruction: `fmacd d13,d25,d31'
kernel_dgemm_4x4_lib4.S:153: Error: no such instruction: `fldd d25,[r5,'
kernel_dgemm_4x4_lib4.S:154: Error: no such instruction: `fmacd d14,d26,d31'
kernel_dgemm_4x4_lib4.S:155: Error: no such instruction: `fldd d26,[r5,'
kernel_dgemm_4x4_lib4.S:156: Error: no such instruction: `fmacd d15,d27,d31'
kernel_dgemm_4x4_lib4.S:157: Error: no such instruction: `fldd d27,[r5,'
kernel_dgemm_4x4_lib4.S:158: Error: no such instruction: `fldd d31,[r6,'
kernel_dgemm_4x4_lib4.S:163: Error: no such instruction: `fmacd d0,d16,d20'
kernel_dgemm_4x4_lib4.S:164: Error: no such instruction: `pld [r6,'
kernel_dgemm_4x4_lib4.S:165: Error: no such instruction: `fmacd d1,d17,d20'
kernel_dgemm_4x4_lib4.S:166: Error: too many memory references for `add'
kernel_dgemm_4x4_lib4.S:167: Error: no such instruction: `fmacd d2,d18,d20'
kernel_dgemm_4x4_lib4.S:168: Error: no such instruction: `fmacd d3,d19,d20'
kernel_dgemm_4x4_lib4.S:169: Error: no such instruction: `fldd d20,[r6,'

**Comment by giaf** [comment]
Just to be sure, are you cross-compiling?
The makefile is intended for native compilation on the ARM device.
If you are cross-compiling, you likely need a different procedure.

**Comment by yongjong111** [comment]
Thank you very much.
It's very helpful.
I'm earlier for this.
so, Can I compile with Android Studio NDK? or using gcc on Android Phone?
and could could you send me prebuilt libraries for arm v7 or armv8?

**Comment by yongjong111** [comment]
I'm using openblas for now.
It's very faster than original.
But It's very interested in your paper against openblas.
I knew that your method is very effective for small size matrix.
we are using A = 1024*48, B = 192*48 or A=384*96, B=96*256 matrix multiplication.
so, I'm going to use blasfeo_sgemm.
In this case, how many fast than openblas?

**Comment by yongjong111** [comment]
sorry, A = 1024 x 48, B = 192 x 48    or A = 384 x 96  , B = 96 x 256
we are going to calculate A x B.
thanks in advance

**Comment by tmmsartor** [comment]
You should be able to cross-compile with android ndk, you can try following this [tutorial](http://nickdesaulniers.github.io/blog/2016/07/01/android-cli/).
We are planning a more standard way to provide binaries for multiple platforms,
for now you can try [this](https://github.com/giaf/blasfeo/files/2000312/libblasfeo.zip). I compiled on a ARM V7 Cortex A15.

**Comment by yongjong111** [comment]
thanks for your attention.
I have received your library and i'll test on my devices.
And also, I have followed your tutorial.
just installed android ndk r17 for linux.
in your tutorial, compiled with clang.
ex; /arm/bin/clang -pie hello_world.c
but blasfeo is directory.
it's not possible /arm/bin/clang -pie ../blasfeo-master.
could you help me more detailed?

**Comment by yongjong111** [comment]
I have tested your library on Armv7 cortexa-17 but not working.
is it only for cortex a 15?

**Comment by yongjong111** [comment]
oh, i fixed that error.
it was M x N x K = 1024 x 512 x 1

**Comment by yongjong111** [comment]
Dear tmmsartor.
I resolved my self, it was parameter mistake.
when packing, lda and ldb value is a little complex for me.
and also, I compared with openblas for blasfeo_sgemm_nn vs cblas_sgemm
- when matrix size A=16384 x 25, B = 25 x 96, 
it's 1.5~2 times fater than openblas in real matrix operation, but unpacking time takes long, so totally it's similar to openblas.
- when matrix size A=384 x 192, B = 192 x 1024, 
it's 2 times slower than openblas without unpacking.
my testing is right?
if there are some mistake, let me know.
Actually, I need to speedup sgemm function for A=12544 x 64, B= 64 x 64
Could you let me know your result?

**Comment by giaf** [comment]
Hi there,

let me clarify a few points to help you understand your findings.

BLASFEO is not intended to be a general-purpose replacement of BLAS (specifically, OpenBLAS in your case). 
By design, BLASFEO targets a special application, namely computations on small matrices where the entire algorithm (or most of it) is implemented using BLASFEO matrix format (therefore avoiding as much as possible matrix packing and unpacking). Typically this is the case in embedded optimization, hence the choice of the name BLASFEO. You can find more details about that in the paper.
BLASFEO may or may not perform well for larger matrices, but it is not what it is designed for: as an example, it does not employ any cache blocking.

In your example, some matrix dimensions are in the order of thousands or tens of thousands, which is much more than the BLASFEO target sizes (in the order of tens or a few hundreds).
By the way the gemm algorithm works internally, BLASFEO still gives good performance regardless of the size of A as long as the matrix B is small (e.g. 25x96 or 64x64 are ok, 192x1024 is surely too large).
But this if your data is already in BLASFEO format (because it comes from another BLASFEO routine, or because it is directly build in that way). If you need to pack forth and back before each call to BLASFEO routines, it is most likely not worthwhile with respect to e.g. OpenBLAS.

Hope this helps to interpret your findings.

**Comment by yongjong111** [comment]
thanks.
it's very helpful.

**Comment by lixiaohang** [comment]
> You should be able to cross-compile with android ndk, you can try following this [tutorial](http://nickdesaulniers.github.io/blog/2016/07/01/android-cli/).
> We are planning a more standard way to provide binaries for multiple platforms,
> for now you can try [this](https://github.com/giaf/blasfeo/files/2000312/libblasfeo.zip). I compiled on a ARM V7 Cortex A15.

Hi ,does this lib can run on Android ?

**Comment by tmmsartor** [comment]
Yes, theoretically, but we never tested that yet, to my knowledge. Have you ever tried @giaf?

**Comment by lixiaohang** [comment]
> Hi there,
> 
> let me clarify a few points to help you understand your findings.
> 
> BLASFEO is not intended to be a general-purpose replacement of BLAS (specifically, OpenBLAS in your case).
> By design, BLASFEO targets a special application, namely computations on small matrices where the entire algorithm (or most of it) is implemented using BLASFEO matrix format (therefore avoiding as much as possible matrix packing and unpacking). Typically this is the case in embedded optimization, hence the choice of the name BLASFEO. You can find more details about that in the paper.
> BLASFEO may or may not perform well for larger matrices, but it is not what it is designed for: as an example, it does not employ any cache blocking.
> 
> In your example, some matrix dimensions are in the order of thousands or tens of thousands, which is much more than the BLASFEO target sizes (in the order of tens or a few hundreds).
> By the way the gemm algorithm works internally, BLASFEO still gives good performance regardless of the size of A as long as the matrix B is small (e.g. 25x96 or 64x64 are ok, 192x1024 is surely too large).
> But this if your data is already in BLASFEO format (because it comes from another BLASFEO routine, or because it is directly build in that way). If you need to pack forth and back before each call to BLASFEO routines, it is most likely not worthwhile with respect to e.g. OpenBLAS.
> 
> Hope this helps to interpret your findings.


> Hi there,
> 
> let me clarify a few points to help you understand your findings.
> 
> BLASFEO is not intended to be a general-purpose replacement of BLAS (specifically, OpenBLAS in your case).
> By design, BLASFEO targets a special application, namely computations on small matrices where the entire algorithm (or most of it) is implemented using BLASFEO matrix format (therefore avoiding as much as possible matrix packing and unpacking). Typically this is the case in embedded optimization, hence the choice of the name BLASFEO. You can find more details about that in the paper.
> BLASFEO may or may not perform well for larger matrices, but it is not what it is designed for: as an example, it does not employ any cache blocking.
> 
> In your example, some matrix dimensions are in the order of thousands or tens of thousands, which is much more than the BLASFEO target sizes (in the order of tens or a few hundreds).
> By the way the gemm algorithm works internally, BLASFEO still gives good performance regardless of the size of A as long as the matrix B is small (e.g. 25x96 or 64x64 are ok, 192x1024 is surely too large).
> But this if your data is already in BLASFEO format (because it comes from another BLASFEO routine, or because it is directly build in that way). If you need to pack forth and back before each call to BLASFEO routines, it is most likely not worthwhile with respect to e.g. OpenBLAS.
> 
> Hope this helps to interpret your findings.

Hi ，giaf
   I use the demo in examples/example_s_lu_factorization.c , I want to use the blasfeo_sgemm_nn ,but I test the time is much more than Openblas,but if I use blasfeo_sgemm_nt ,the time is less than OpenBLAS,WHy? is the type I pack the Mat ? My code is like This ::
	int ii;
	int n = 200;
	float *A; s_zeros(&A, n, n);
	for(ii=0; ii<n*n; ii++) A[ii] = ii;
	float *B; s_zeros(&B, n, n);
       for (ii = 0; ii < n*n; ii++) B[ii] = n*n+ii;
       float *C; s_zeros(&C, n, n);

	int size_strmat = 5*blasfeo_memsize_smat(n, n);
	void *memory_strmat; v_zeros_align(&memory_strmat, size_strmat);
	char *ptr_memory_strmat = (char *) memory_strmat;

	struct blasfeo_smat sA;
	blasfeo_create_smat(n, n, &sA, ptr_memory_strmat);
	ptr_memory_strmat += sA.memsize;
	blasfeo_pack_smat(n, n, A, n, &sA, 0, 0);

	struct blasfeo_smat sB;
	blasfeo_create_smat(n, n, &sB, ptr_memory_strmat);
	ptr_memory_strmat += sB.memsize;
	blasfeo_pack_smat(n, n, B, n, &sB, 0, 0);

       struct blasfeo_smat sC;
      blasfeo_create_smat(n, n, &sC, ptr_memory_strmat);
       ptr_memory_strmat += sC.memsize;
       blasfeo_pack_smat(n, n, C, n, &sC, 0, 0);
        //C= A*B
        blasfeo_sgemm_nn(n, n, n, 1.0, &sA, 0, 0, &sB, 0, 0, 0.0, &sB, 0, 0, &sC, 0, 0);
        //the C= A*B'
       //blasfeo_sgemm_nt(n, n, n, 1.0, &sA, 0, 0, &sB, 0, 0, 0.0, &sB, 0, 0, &sC, 0, 0);


SO ,it because I pack the data to Column ？ so the   **blasfeo_sgemm_nn** need much more time than **blasfeo_sgemm_nt** ?

**Comment by tmmsartor** [comment]
Hi lixiaohang,
Wich `TARGET` are you using?
Not all single precision routines are optimized for every target,
for example on `ARMV8A_ARM_CORTEX_A53` **sgemm_nn** is not optimized while **sgemm_nt** it is,
you can see this and the comparison with OpenBlas on [our website](https://blasfeo.syscop.de/comparisons/cortexa53/#gemm) (click on routine name to show the plot)

**Comment by lixiaohang** [comment]
Hi :
I use the target ARMv8A ARM Cortex A57,But I compile and run on Android Phone

**Comment by tmmsartor** [comment]
As you can in the following image from [the website](https://blasfeo.syscop.de/comparisons/cortexa57/)
) the situation is the same for A57:
![image](https://user-images.githubusercontent.com/746627/56644139-63082700-667b-11e9-9366-f75f2cb64764.png)
So for your application you need **sgemm_nn** specifically? 
If this is the case maybe we can talk about speeding up the development of that routine.

**Comment by lixiaohang** [comment]
Hi :
 My application is for kalman filter ,it has many Matrix multiply  like A*B*A.transpose() ,so I need sgemm_nn and sgemm_nt ,so ,can you speed up the sgemm_nn?

**Comment by giaf** [comment]
I am on holiday and I do not have the hardware with me, I can have a look when I get back.

**Comment by giaf** [comment]
I made some work to improve performance of `sgemm_nn`. You should already see some nice speed up, even if the optimization is not completed yet.
