### ISSUE TITLE
Stable branch

### ISSUE THREAD

**Issue by zanellia** [giaf/blasfeo#6]
Shall we have a stable branch? We could make one based on the commit currently used in acados. Or we could have master and develop.

**Comment by giaf** [comment]
maybe I like more the idea of adding a stable branch (e.g. based on unoptimized kernels in single precision, since the optimized ones are still work in progress)

**Comment by giaf** [comment]
we got one ;)

**Comment by mkatliar** [comment]
> we got one ;)

What is the name?
