### ISSUE TITLE
blasfeo_dgead - Bug in Sandy Bridge implementation offset 15,    0

### ISSUE THREAD

**Issue by FreyJo** [giaf/blasfeo#60]
Hey guys,

I think I found a Bug in the Sandy Bridge implementation of blasfeo_dgead.
Namely when using the function
`void blasfeo_dgead(int m, int n, double alpha, struct blasfeo_dmat *sA, int ai, int aj, struct blasfeo_dmat *sC, int ci, int cj)`
with
`m = 5, n = 8,  ci = 15, cj = 0.`
It seems like the corresponding block is not added, the entries stay zero in contrast to the Generic implementation, where it works fine..

Should help to find the bug..
Best

**Comment by giaf** [comment]
@tmmsartor could you check this one? Thanks!

**Comment by tmmsartor** [comment]
#61 should fix this, also #56 is ready to be merged.

**Comment by giaf** [comment]
great, thanks!
