### ISSUE TITLE
Variable size arrays in examples (see acados failing appveyor build for instances)

### ISSUE THREAD

**Issue by dkouzoup** [giaf/blasfeo#65]
It would be great to either eliminate those or provide a cmake variable to compile blasfeo without the examples.

**Comment by dkouzoup** [comment]
the errors can be found here:

https://ci.appveyor.com/project/roversch/acados/build/1.0.459

Note that the more we delay this and the continuous integration fails, the more errors will accumulate. Already the latest master has a bunch of new errors. @bnovoselnik maybe you can create a quick PR for this one?

**Comment by bnovoselnik** [comment]
I'm on it!

**Comment by bnovoselnik** [comment]
PR #67 should do it

**Comment by dkouzoup** [comment]
oh that was fast! Thanks! Can you also check these newer syntax errors at the end of this log maybe?

https://ci.appveyor.com/project/dkouzoup/acados/build/1.0.436

are they easy to fix?

**Comment by bnovoselnik** [comment]
These seem to be caused by the use of GCC's __attribute__ mechanism (which is not implemented in Visual Studio). I guess some kind of preprocessing macro could be used to circumvent this. I'll give it a try.

**Comment by dkouzoup** [comment]
Thanks! It must have been introduced recently because the previous version of blasfeo coupled to acados did not produce these errors.

**Comment by bnovoselnik** [comment]
OK, so according to the link below, in VS 2015 and later supports this:

```c
__declspec( align( # ) )
```
which should be equivalent to GCC's

```c
__attribute__ ((aligned (#)))
```


link: https://msdn.microsoft.com/en-us/library/83ythb65.aspx

So I added a small macro CACHE_ALIGN(X) in the latest commit that uses the first one in case Visual Studio is detected and the second one otherwise (thankfully, GCC and clang have the same implementation).

**Comment by dkouzoup** [comment]
Awesome! Thanks @bnovoselnik. @giaf  can you please check and merge this one? I will then check if Appveyor succeeds in acados.

**Comment by dkouzoup** [comment]
Can't really test it but closing for now.
