### ISSUE TITLE
Generic implementation functions wrong number of arguments

### ISSUE THREAD

**Issue by twanvandersijs** [giaf/blasfeo#76]
When manually compiling the generic kernel implementation, there are a few functions that have a mismatch in the number of arguments in the header and the source (and/or different argument or return types). The functions are:

kernel_dgemm_diag_left_4_a0_lib4
kernel_dgemm_diag_left_4_lib4
kernel_dlarf_t_4_lib4
kernel_strcp_l_2_0_lib4
kernel_sgemm_diag_left_4_a0_lib4
kernel_sgemm_diag_left_4_lib4

It seems that some have been changed in the avx implementation a while ago (e.g. kernel_dlarf_t_4_lib4 in 4604ddc  on Apr 25, 2017) but not in the generic.

**Comment by giaf** [comment]
Thank you for pointing it out. This should fix it https://github.com/giaf/blasfeo/commit/90948b35a36b10fb9e45674a60fc99252485377a

**Comment by twanvandersijs** [comment]
Jup, it is fixed. Thank you!
