### ISSUE TITLE
invalid reads

### ISSUE THREAD

**Issue by twanvandersijs** [giaf/blasfeo#83]
When running valgrind on the d_riccati_recursion example,

it returns invalid read errors in the functions:
blasfeo_dtrmv_lnn (d_blas2_lib4.c:575) and blasfeo_pack_tran_dmat (d_aux_lib4.c:2184)

**Comment by giaf** [comment]
@tmmsartor any idea about that?

**Comment by tmmsartor** [comment]
I will look in to this, @twanvandersijs  which `TARGET` are you using?

**Comment by twanvandersijs** [comment]
The generic target, but the x64_intel_haswell has it as well.

**Comment by tmmsartor** [comment]
@twanvandersijs which branch and with OS?
What was exactly the error?
On branch `stable` running from linux I am not able to replicate the error. 
I will try anyway to check what is happening on those lines.

**Comment by twanvandersijs** [comment]
That is strange, I used ubuntu 16.04 with the master branch and I tried the stable as well. Both seem to have the invalid reads in them. I attached the valgrind output I got with the stable branch.
[log.txt](https://github.com/giaf/blasfeo/files/2685331/log.txt)
.

**Comment by tmmsartor** [comment]
There was some problems, it should be fixed now, can you try to pull the stable branch and see if it's now fixed also for you?

**Comment by twanvandersijs** [comment]
@roversch fyi

**Comment by giaf** [comment]
closing this
