### ISSUE TITLE
not implemented: blasfeo_strsv_lnu and blasfeo_strsv_unn

### ISSUE THREAD

**Issue by roversch** [giaf/blasfeo#95]
Apparently, `blasfeo_strsv_lnu` and `blasfeo_strsv_unn` are not implemented for high-performance linear algebra.

Is it on the roadmap anytime soon?

**Comment by roversch** [comment]
Same goes for `blasfeo_sgetrf_rp` by the way.

**Comment by giaf** [comment]
Very little stuff is implemented in single precision, pretty much only (some version of) sgemm and what is needed in HPIPM's Riccati recursion. The only planned addition on the roadmap is the BLAS_API sgemm routine.

These routine are not really on the roadmap, unless there is a strong case for it (e.g. some sort of project or collaboration).

**Comment by roversch** [comment]
okay, that is clear, thanks.
