### ISSUE TITLE
Downgrade default target

### ISSUE THREAD

**Issue by FreyJo** [giaf/blasfeo#96]
Hi,

I have a reasonably new Laptop with the following CPU:
Intel® Core™ i7-3520M CPU @ 2.90GHz × 4
and Ubuntu 18.04.

Unfortunately, the new default target (X64_INTEL_HASWELL) does not work for me.
I think it would be good to downgrade the default target to SANDY_BRIDGE or GENERIC, in order to reduce the installation effort of HPIPM.

**Comment by giaf** [comment]
The reasonably new Laptop has a ~7 years old processor, and you are the only one I know with a pre-Haswell architecture ;)

**Comment by giaf** [comment]
And you will likely get a new one in a couple of weeks ;)
